# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd0e6fe138d06fc95f8a6e17e0f63685b245dd4fec82f68b483a5c13dae76708ac3f3865fbcc72632220635a03906576a6c60233629831f0138be06df5879dcd

test:
  secret_key_base: 9e3a0cf79b905b39eb94a3f3b6986491bc27721406b5843bae4fc82a9d2f6119ff582ba79e2019e94056de7b09cce512ea3e491050a302a49da18f349bc32cb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
